name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-Vue
      run: |
        yarn install --frozen-lockfile
        yarn build
        cd dist
        git config --global user.email "CI@github.com"
        git config --global user.name "CI"
        git init
        git add -A
        git commit -m 'auto commit ${{ github.sha }}'
        git push -f master:gh-pages